mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('vDate.urls')),
]

vDate/urls.py
from django.conf.urls import url
from . import views
"""
Django URL Dispatcher.
Allocates view to URLs.
"""
urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^boys/$', views.boys, name='boys'),
	url(r'^girls/$', views.girls, name='girls'),
	url(r'^gifts/$', views.gifts, name='gifts'),
	url(r'^relations/$', views.relations, name='relations'),
    url(r'^delete/$', views.deleteEntries, name='delete'),
]

vDate/models.py
from django.db import models
from django import forms
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils import timezone
from datetime import datetime
from .constants import *
from decimal import *
import math

"""
Created on 26 February 2017
.. module:: models
	:platform: Unix, Windows
	:synopsis: All the classes(models).
.. projectauthor:: Raghav Khandelwal <LIT2015002>
"""

class Girl(models.Model):
	"""
	Class representing the Girl Object with all its attributes
	"""
	name = models.CharField(max_length=100)
	attractiveness = models.FloatField(validators=[MinValueValidator(1), MaxValueValidator(10)])
	intelligenceLevel = models.FloatField(validators=[MinValueValidator(1), MaxValueValidator(10)])
	isCommitted = models.BooleanField(default=False)
	maintenanceBudget = models.DecimalField(max_digits=13, decimal_places=2)
	datingCriteria = models.IntegerField(choices=datingCriteriaChoices)
	girlType = models.IntegerField(choices=committedGirlTypes, default=None)
	
	def __str__(self):
		return self.name
		
	def commit(self):
		self.isCommitted = True
		self.save()

	def leave(self):
		self.isCommitted = False
		self.save()
	
class Boy(models.Model):
	"""
	Class representing the Boy Object with all its attributes
	"""
	name = models.CharField(max_length=100)
	attractiveness = models.FloatField(validators=[MinValueValidator(1), MaxValueValidator(10)])
	intelligenceLevel = models.FloatField(validators=[MinValueValidator(1), MaxValueValidator(10)])
	isCommitted = models.BooleanField(default=False)
	budget = models.DecimalField(max_digits=13, decimal_places=2)
	attractionRequirement = models.FloatField(validators=[MinValueValidator(1), MaxValueValidator(10)])
	boyType = models.IntegerField(choices=committedBoyTypes, default=None)
	
	def __str__(self):
		return self.name
		
	def commit(self):
		self.isCommitted = True
		self.save()

	def leave(self):
		self.isCommitted = False
		self.save()

	def increaseBudget(self, increase):
		budget = budget + increase;


class EssentialGift(models.Model):
	"""
	Class representing the Essential Gift Object with all its attributes
	"""
	price = models.DecimalField(max_digits=13, decimal_places=2)
	value = models.FloatField()

	def __str__(self):
		return "Price: " + str(self.price) + ", Value: " + str(self.value)

class LuxuryGift(models.Model):
	"""
	Class representing the Luxury Gift Object with all its attributes
	"""
	price = models.DecimalField(max_digits=13, decimal_places=2)
	value = models.FloatField()
	luxuryRating = models.FloatField()
	difficultyToObtain = models.FloatField()

	def __str__(self):
		return "Price: " + str(self.price) + ", Value: " + str(self.value)

class UtilityGift(models.Model):
	"""
	Class representing the Utility Object with all its attributes
	"""
	price = models.DecimalField(max_digits=13, decimal_places=2)
	value = models.FloatField()
	utilityValue = models.FloatField()
	utilityClass = models.IntegerField(choices=utilityClasses)

	def __str__(self):
		return "Price: " + str(self.price) + ", Value: " + str(self.value)

class Relation(models.Model):
	"""
	Class representing the Relation Object with all its attributes, which represents the relation between committed boys and girls.
	Supports breakup and finding compatibility, happiness, etc.
	"""
	boy = models.ForeignKey(Boy, on_delete=models.CASCADE)
	girl = models.ForeignKey(Girl, on_delete=models.CASCADE)
	commitOn = models.DateTimeField(default=timezone.now)
	breakupOn = models.DateTimeField(blank=True, null=True)
	compatibility = models.FloatField(default=0)
	happiness = models.FloatField(blank=True, null=True)

	def __str__(self):
		if self.breakupOn is None:
			return "%s + %s" % (self.girl.name, self.boy.name)
		return "%s was with %s" % (self.girl.name, self.boy.name)

	def breakup(self):
		"""
		Breaks up relationship. Sets girl and boy to not committed.

		:param self: Object of type Relation
		"""
		self.breakupOn = datetime.now()
		self.girl.leave()
		self.boy.leave()
		self.delete()

	def findCompatibility(self):
		"""
		Finds compatibility between girl and boy in a relationship.

		:param self: Object of type Relation
		"""
		self.compatibility = (self.boy.budget - self.girl.maintenanceBudget) + Decimal(abs(self.boy.attractiveness - self.boy.attractiveness)) + Decimal(abs(self.boy.intelligenceLevel - self.girl.intelligenceLevel))
		self.save()
		return self.compatibility

	def findHappiness(self):
		"""
		Calculates girl and boy happiness to find happiness of couple.

		:param self: Object of type Relation
		:returns: Happiness of couple
		"""
		total_cost = Decimal(0)
		gifts = self.exchanges.all()
		for gift in gifts:
			total_cost = total_cost + gift.getGift().price

		if self.girl.girlType == 1:
			for gift in gifts:
				if gift.giftType == 2:
					total_cost = total_cost + gift.getGift().price
			girlHappiness = math.log(total_cost - self.girl.maintenanceBudget)
		elif self.girl.girlType == 2:
			for gift in gifts:
				total_cost = total_cost + Decimal(gift.getGift().value)
			girlHappiness = total_cost - self.girl.maintenanceBudget
		elif self.girl.girlType == 3:
			try:
				girlHappiness = math.exp(total_cost - self.girl.maintenanceBudget)
			except OverflowError:
				girlHappiness = float('inf')

		if self.boy.boyType == 1:
			boyHappiness = self.boy.budget - total_cost
		elif self.boy.boyType == 2:
			boyHappiness = girlHappiness
		elif self.boy.boyType == 3:
			boyHappiness = self.girl.intelligenceLevel

		self.happiness = float(boyHappiness) + float (girlHappiness)
		self.save()
		return self.happiness


class Exchange(models.Model):
	"""
	Class representing the Exchange Object with all its attributes.

	It models all the gift tranfers between the boy and the girl and the time stamp at which the exchange took place. Supports all 3 type of gifts.
	"""
	relation = models.ForeignKey('vDate.Relation', related_name='exchanges')
	essentialGift = models.ForeignKey('vDate.EssentialGift', blank=True, null=True)
	luxuryGift = models.ForeignKey('vDate.LuxuryGift', blank=True, null=True)
	utilityGift = models.ForeignKey('vDate.UtilityGift', blank=True, null=True)
	giftType = models.IntegerField(choices=giftTypes, default=None)
	exchangeTime = models.DateTimeField(default = timezone.now)

	def __str__(self):
		return "%s got gift worth %.2f from %s on %s" % (self.relation.girl.name, self.getGift().price, self.relation.boy.name, self.exchangeTime)

	def getGift(self):
		"""
		Returns the appropriate gift type.

		:param self: Object of type Exchange
		:returns: Type of gift in exchange 
		"""
		if self.giftType == 1:
			return self.essentialGift
		elif self.giftType == 2:
			return self.luxuryGift
		elif self.giftType == 3:
			return self.utilityGift
		else:
			return None

vDate/forms.py
from django import forms
from .models import *
from .constants import *

"""
All the forms used by the HTML Templates and Django Views are declared here.
"""
class GetNumberForm(forms.Form):
	number = forms.IntegerField(max_value=200)

class GetGiftNumberForm(forms.Form):
	giftType = forms.ChoiceField(choices=giftTypes, required=True)
	number = forms.IntegerField(max_value=200)

class BoyForm(forms.ModelForm):
	boyType = forms.ChoiceField(choices=committedBoyTypes, required=True)

	class Meta:
		model = Boy
		fields = ('name', 'attractiveness', 'intelligenceLevel', 'isCommitted', 'budget', 'attractionRequirement', 'boyType')
		help_texts = {
			'attractiveness': 'Between 1 to 10',
			'intelligenceLevel': 'Between 1 to 10',
			'attractionRequirement': 'Between 1 to 10',
		}

class GirlForm(forms.ModelForm):
	girlType = forms.ChoiceField(choices=committedGirlTypes, required=True)

	class Meta:
		model = Girl
		fields = ('name', 'attractiveness', 'intelligenceLevel', 'isCommitted', 'maintenanceBudget', 'datingCriteria', 'girlType')
		help_texts = {
			'attractiveness': 'Between 1 to 10',
			'intelligenceLevel': 'Between 1 to 10',
		}

class EssentialGiftForm(forms.ModelForm):
	class Meta:
		model = EssentialGift
		fields = ('price', 'value')

class LuxuryGiftForm(forms.ModelForm):
	class Meta:
		model = LuxuryGift
		fields = ('price', 'value', 'luxuryRating', 'difficultyToObtain')

class UtilityGiftForm(forms.ModelForm):
	utilityClass = forms.ChoiceField(choices=utilityClasses, required=True)
	
	class Meta:
		model = UtilityGift
		fields = ('price', 'value', 'utilityValue', 'utilityClass')

class RelationForm(forms.ModelForm):
	class Meta:
		model = Relation
		fields = ('boy', 'girl', 'commitOn', 'breakupOn')

vDate/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import *
from .forms import *
from vDate.new import *

"""
These views serve all the data to the front-end templates.
"""

def home(request):
	exchangesList = Exchange.objects.all()
	happyCouples = Relation.objects.all().order_by('-happiness')
	compatibleCouples = Relation.objects.all().order_by('-compatibility')
	return render(request, 'vDate/Q2.html', {'happyCouples': happyCouples, 'compatibleCouples': compatibleCouples})

def boys(request):
	"""
	Prints list of all boys.
	Using POST form recieves the number of random entries to generate for the boy class.
	Can create a custom Boy using another POST form.
	"""
	manual = False	
	boyForm = BoyForm(prefix='manual')
	if request.method == 'POST':
		boyForm = BoyForm(request.POST, prefix='manual')
		if boyForm.is_valid():
			boyForm.save()
			manual = True
		numForm = GetNumberForm(request.POST, prefix='auto')
		if not manual and numForm.is_valid():
			number = numForm.cleaned_data['number']
			if isinstance(number, int):
				for i in range(number):
					newRandomBoy()
			boyForm = BoyForm(prefix='manual')
	numForm = GetNumberForm(prefix='auto')
	boysList = Boy.objects.all().order_by('name')
	return render(request, 'vDate/boys.html', {'boysList': boysList, 'boyForm': boyForm, 'getNumberForm': numForm})

def girls(request):
	"""
	Prints list of all girls.
	Using POST form recieves the number of random entries to generate for the girl class.
	Can create a custom Girl using another POST form.
	"""
	manual = False	
	girlForm = GirlForm(prefix='manual')
	if request.method == 'POST':
		girlForm = GirlForm(request.POST, prefix='manual')
		if girlForm.is_valid():
			girlForm.save()
			manual = True
		numForm = GetNumberForm(request.POST, prefix='auto')
		if not manual and numForm.is_valid():
			number = numForm.cleaned_data['number']
			for i in range(number):
				newRandomGirl()
			girlForm = GirlForm(prefix='manual')
	numForm = GetNumberForm(prefix='auto')
	girlsList = Girl.objects.all().order_by('name')
	return render(request, 'vDate/girls.html', {'girlsList': girlsList, 'girlForm': girlForm, 'getNumberForm': numForm})


def gifts(request):
	"""
	Prints list of all Gifts- Essential, Luxury and Utility Gifts.
	Using POST form recieves the number of random entries to generate for the a particular gift class.
	Can create a custom Gifts of required type using 3 other POST forms.
	"""
	handled = False
	giftNumForm = GetGiftNumberForm(prefix='auto')
	essentialGiftForm = EssentialGiftForm(prefix='essentialGift')
	luxuryGiftForm = LuxuryGiftForm(prefix='luxuryGift')
	utilityGiftForm = UtilityGiftForm(prefix='utilityGift')
	if request.method == 'POST':
		giftNumForm = GetGiftNumberForm(request.POST, prefix='auto')
		if giftNumForm.is_valid():
			handled = True
			giftType = giftNumForm.cleaned_data['giftType']
			number = giftNumForm.cleaned_data['number']
			for i in range(number):
				if giftType == '1':
					newEssentialGift()
				elif giftType == '2':
					newLuxuryGift()
				elif giftType == '3':
					newUtilityGift()
		if not handled:
			essentialGiftForm = EssentialGiftForm(request.POST, prefix='essentialGift')
			if essentialGiftForm.is_valid():
				handled = True
				essentialGiftForm.save()
		if not handled:
			luxuryGiftForm = LuxuryGiftForm(request.POST, prefix='luxuryGift')
			if luxuryGiftForm.is_valid():
				handled = True
				luxuryGiftForm.save()
		if not handled:	
			utilityGiftForm = UtilityGiftForm(request.POST, prefix='utilityGift')
			if utilityGiftForm.is_valid():
				utilityGiftForm.save()
				handled = True
	if handled:
		giftNumForm = GetGiftNumberForm(prefix='auto')
		essentialGiftForm = EssentialGiftForm(prefix='essentialGift')
		luxuryGiftForm = LuxuryGiftForm(prefix='luxuryGift')
		utilityGiftForm = UtilityGiftForm(prefix='utilityGift')
	essentialGiftsList = EssentialGift.objects.all().order_by('price')
	luxuryGiftsList = LuxuryGift.objects.all().order_by('price')
	utilityGiftsList = UtilityGift.objects.all().order_by('price')
	return render(request, 'vDate/gifts.html',{
		'essentialGiftsList': essentialGiftsList,
		'luxuryGiftsList': luxuryGiftsList,
		'utilityGiftsList': utilityGiftsList,
		'essentialGiftForm': essentialGiftForm,
		'luxuryGiftForm': luxuryGiftForm,
		'utilityGiftForm': utilityGiftForm,
		'giftNumberForm': giftNumForm
		})

def relations(request):
	"""
	Prints list of all the relations currently existing.
	Using POST form recieves the number of random relations to create subject to availability of suitable matches.
	"""
	relationsList = Relation.objects.all()
	exchangesList = Exchange.objects.all()
	handled = False
	if exchangesList.exists():
		status = True
	else:
		status = False
	numForm = GetNumberForm()
	if request.method == 'POST':
		numForm = GetNumberForm(request.POST)
		if numForm.is_valid():
			handled = True
			number = numForm.cleaned_data['number']
			girlCount = Girl.objects.filter(isCommitted=False).count()
			if number > girlCount:
				messages.error(request, "Not enough single girls!")
			else:
				girlList = Girl.objects.filter(isCommitted=False)[:number]	
				for girl in girlList:
					findMatch(girl)
		elif not handled and request.POST.get('type') == 'gifting':
			handled = True
			if status:
				messages.error(request, "Gifting Already Performed!")
			else:
				for relation in Relation.objects.all():
					performGifting(relation)
					relation.findHappiness()
	if handled:
		numForm = GetNumberForm()
	return render(request, 'vDate/relations.html', {
		'relationsList': relationsList,
		'exchangesList': exchangesList,
		'getNumberForm': numForm,
		'status': status,
		})

def deleteEntries(request):
	"""
	Purpose of this View is to serve the "Delete all" button at the end of all pages to get rid of the records and insert new records to database.
	"""
	if request.method == 'POST':
		if request.POST.get('type') == 'boys':
			Boy.objects.all().delete()
			return HttpResponseRedirect(reverse('boys'))
		elif request.POST.get('type') == 'girls':
			Girl.objects.all().delete()
			return HttpResponseRedirect(reverse('girls'))
		elif request.POST.get('type') == 'gifts':
			EssentialGift.objects.all().delete()
			LuxuryGift.objects.all().delete()
			UtilityGift.objects.all().delete()
			return HttpResponseRedirect(reverse('gifts'))
		elif request.POST.get('type') == 'relations':
			for relation in Relation.objects.all():
				relation.breakup()
			return HttpResponseRedirect(reverse('relations'))
	return HttpResponseRedirect(reverse('home'))

vDate/templates/vDate/boys.html
{% extends 'vDate/base.html' %}
{% load humanize %}
{% block content %}
<section class="row header-row">
	<div class="col-sm-6">
		<h1>Boys <span class="badge">{{ boysList.count }}</span></h1>
	</div>
	<div class="col-sm-6">	
		<form class="form-inline" method="POST">{% csrf_token %}
			<div class="input-group">
				<input type="number" class="form-control" id="id_auto-number" max="200" name="auto-number" placeholder="Number" required>
				<span class="input-group-btn">
					<button type="submit" class="btn btn-primary">Generate Random Entries</button>
				</span>
			</div>
		</form>
		{{ form.number.errors }}
	</div>
</section>

<section>
	<div class="table-responsive">
		<form method="POST">{% csrf_token %}
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Name</th>
					<th>Attractiveness</th>
					<th>Intelligence</th>
					<th>Committed</th>
					<th>Budget</th>
					<th>Attraction Requirement</th>
					<th>Type</th>
				</tr>
			</thead>
			<tbody>
			{% for boy in boysList %}
			<tr>
				<td>{{ boy.name }}</td>
				<td>{{ boy.attractiveness|floatformat:"-2" }}</td>
				<td>{{ boy.intelligenceLevel|floatformat:"-2" }}</td>
				<td>{{ boy.isCommitted }}</td>
				<td>&#8377; {{ boy.budget|intcomma }}</td>
				<td>{{ boy.attractionRequirement|floatformat:"-2"	 }}</td>
				<td>{{ boy.get_boyType_display }}</td>
			</tr>
			{% endfor %}
			<tr>
				{% for field in boyForm %}
				<td>
					{{ field }}
					{{ field.errors }}
				</td>
				{% endfor %}
			</tr>
			</tbody>
		</table>
		<button type="submit" class="new btn btn-default">New Custom Entry</button>
		</form>
	</div>
	
</section>
<div class="delete-all">
	<form action="{% url 'delete' %}" method="POST">{% csrf_token %}
		<button type="submit" name="type" value="boys" class="btn btn-danger">Delete All</button>
	</form>
</div>
{% endblock %}

vDate/templates/vDate/gifts.html
{% extends 'vDate/base.html' %}
{% load humanize %}
{% block content %}

<section class="row header-row">
	<div class="col-sm-6">
		<h1>Gifts <span class="badge">{{ essentialGiftsList.count|add:luxuryGiftsList.count|add:utilityGiftsList.count }}</span></h1>
	</div>
	<div class="col-sm-6">	
		<form class="form-inline" method="POST">{% csrf_token %}
			<div class="input-group">
				<input id="id_auto-number" class="form-control" max="200" name="auto-number" type="number" placeholder="Number" required/>
				<span class="input-group-addon" style="width:0px; padding-left:0px; padding-right:0px; border:none;"></span>
				<select id="id_auto-giftType" class="form-control" name="auto-giftType" required>
					<option value="1">Essential Gift</option>
					<option value="2">Luxury Gift</option>
					<option value="3">Utility Gift</option>
				</select>
				<span class="input-group-addon" style="width:0px; padding-left:0px; padding-right:0px; border:none;"></span>
				<span class="input-group-btn">
					<button type="submit" class="btn btn-primary">Generate Random Entries</button>
				</span>
			</div>
		</form>
		{{ giftNumberForm.errors }}
	</div>
</section>

<section>
<h3>Essential Gifts <span class="badge">{{ essentialGiftsList.count }}</span></h3>
	<div class="table-responsive">
		<form method="POST">{% csrf_token %}
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Price</th>
					<th>Value</th>
				</tr>
			</thead>
			<tbody>
			{% for gift in essentialGiftsList %}
			<tr>
				<td>&#8377; {{ gift.price|intcomma }}</td>
				<td>{{ gift.value|floatformat:"-1" }}</td>
			</tr>
			{% endfor %}
			<tr>
				{% for field in essentialGiftForm %}
				<td>
					{{ field }}
					{{ field.errors }}
				</td>
				{% endfor %}
			</tr>
			</tbody>
		</table>
		<button type="submit" class="new btn btn-default">New Custom Entry</button>
		</form>
	</div>
</section>
<section>
<h3>Luxury Gifts <span class="badge">{{ luxuryGiftsList.count }}</span></h3>
	<div class="table-responsive">
		<form method="POST">{% csrf_token %}
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Price</th>
					<th>Value</th>
					<th>Luxury Rating</th>
					<th>Difficulty to Obtain</th>
				</tr>
			</thead>
			<tbody>
			{% for gift in luxuryGiftsList %}
			<tr>
				<td>&#8377; {{ gift.price|intcomma }}</td>
				<td>{{ gift.value|floatformat:"-1" }}</td>
				<td>{{ gift.luxuryRating|floatformat:"0" }}</td>
				<td>{{ gift.difficultyToObtain|floatformat:"-1" }}</td>
			</tr>
			{% endfor %}
			<tr>
				{% for field in luxuryGiftForm %}
				<td>
					{{ field }}
					{{ field.errors }}
				</td>
				{% endfor %}
			</tr>
			</tbody>
		</table>
		<button type="submit" class="new btn btn-default">New Custom Entry</button>
		</form>
	</div>
</section>
<section>
<h3>Utility Gifts <span class="badge">{{ utilityGiftsList.count }}</span></h3>
	<div class="table-responsive">
		<form method="POST">{% csrf_token %}
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Price</th>
					<th>Value</th>
					<th>Utility Rating</th>
					<th>Utility Class</th>
				</tr>
			</thead>
			<tbody>
			{% for gift in utilityGiftsList %}
			<tr>
				<td>&#8377; {{ gift.price|intcomma }}</td>
				<td>{{ gift.value|floatformat:"-1" }}</td>
				<td>{{ gift.utilityValue|floatformat:"0" }}</td>
				<td>{{ gift.get_utilityClass_display}}</td>
			</tr>
			{% endfor %}
			<tr>
				{% for field in utilityGiftForm %}
				<td>
					{{ field }}
					{{ field.errors }}
				</td>
				{% endfor %}
			</tr>
			</tbody>
		</table>
		<button type="submit" class="new btn btn-default">New Custom Entry</button>
		</form>
	</div>
</section>
<div class="delete-all">
	<form action="{% url 'delete' %}" method="POST">{% csrf_token %}
		<button type="submit" name="type" value="gifts" class="btn btn-danger">Delete All</button>
	</form>
</div>
{% endblock %}

vDate/templates/vDate/girls.html
{% extends 'vDate/base.html' %}
{% load humanize %}
{% block content %}
<section class="row header-row">
	<div class="col-sm-6">
		<h1>Girls <span class="badge">{{ girlsList.count }}</span></h1>
	</div>
	<div class="col-sm-6">	
		<form class="form-inline" method="POST">{% csrf_token %}
			<div class="input-group">
				<input type="number" class="form-control" id="id_auto-number" max="200" name="auto-number" placeholder="Number" required>
				<span class="input-group-btn">
					<button type="submit" class="btn btn-primary">Generate Random Entries</button>
				</span>
			</div>
		</form>
		{{ form.number.errors }}
	</div>
</section>

<section>
	<div class="table-responsive">
		<form method="POST">{% csrf_token %}
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Name</th>
					<th>Attractiveness</th>
					<th>Intelligence</th>
					<th>Committed</th>
					<th>Maintenance Budget</th>
					<th>Dating Criteria</th>
					<th>Type</th>
				</tr>
			</thead>
			<tbody>
			{% for girl in girlsList %}
			<tr>
				<td>{{ girl.name }}</td>
				<td>{{ girl.attractiveness|floatformat:"-2" }}</td>
				<td>{{ girl.intelligenceLevel|floatformat:"-2" }}</td>
				<td>{{ girl.isCommitted }}</td>
				<td>&#8377; {{ girl.maintenanceBudget|intcomma }}</td>
				<td>{{ girl.get_datingCriteria_display }}</td>
				<td>{{ girl.get_girlType_display }}</td>
			</tr>
			{% endfor %}
			<tr>
				{% for field in girlForm %}
				<td>
					{{ field }}
					{{ field.errors }}
				</td>
				{% endfor %}
			</tr>
			</tbody>
		</table>
		<button type="submit" class="new btn btn-default">New Custom Entry</button>
		</form>
	</div>
</section>
<div class="delete-all">
	<form action="{% url 'delete' %}" method="POST">{% csrf_token %}
		<button type="submit" name="type" value="girls" class="btn btn-danger">Delete All</button>
	</form>
</div>
{% endblock %}

vDate/templates/vDate/relations.html
{% extends 'vDate/base.html' %}
{% load humanize %}
{% block content %}
<section class="row header-row">
	<div class="col-sm-6">
		<h1>Relations <span class="badge">{{ relationsList.count }}</span></h1>
	</div>
	<div class="col-sm-4">	
		<form class="form-inline" method="POST">{% csrf_token %}
			
			<div class="input-group">
				<input type="number" class="form-control" id="id_number" max="200" name="number" placeholder="Number" required>
				<span class="input-group-btn">
					<button type="submit" class="btn btn-primary">Q1. Generate Random Entries</button>
				</span>
			</div>
		</form>
		{{ getNumberForm.errors }}
		{% if messages %}
			{% for message in messages %}
			{{ message }}
			{% endfor %}
		{% endif %}
	</div>
	<div class="col-sm-2">
		<form action="{% url 'relations' %}" method="POST">{% csrf_token %}
			<button type="submit" name="type" value="gifting" class="btn btn-primary">Q2. Perform Gifting</button>
		</form>
	</div>
</section>

<section>
	<div class="table-responsive">
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Girl</th>
					<th>Boy</th>
					<th>Committed On</th>
					<th>Compatibility</th>
				</tr>
			</thead>
			<tbody>
			{% for relation in relationsList %}
			<tr>
				<td>{{ relation.girl.name }}</td>
				<td>{{ relation.boy.name }}</td>
				<td>{{ relation.commitOn }}</td>
				<td>{{ relation.compatibility|floatformat:"-2" }}</td>
			</tr>
			{% if status %}
			<tr>
				<td><h4>Exchanges</h4></td>
				<td colspan="3">
					<table class="table table-striped">
					{% for exchange in exchangesList %}
					{% if exchange.relation == relation %}
					<tr>
						<td>{{ exchange.get_giftType_display }}</td>
						<td>&#8377; {{ exchange.getGift.price|intcomma }}</td>
						<td>{{ exchange.exchangeTime }}</td>
					</tr>
					{% endif %}
					{% endfor %}
					</table>
				</td>
			</tr>
			{% endif %}
			{% endfor %}
			</tbody>
		</table>
	</div>
</section>
<div class="delete-all">
	<form action="{% url 'delete' %}" method="POST">{% csrf_token %}
		<button type="submit" name="type" value="relations" class="btn btn-danger">Delete All</button>
	</form>
</div>
{% endblock %}